### ISSUE TITLE
Optional fields in composite field parser issue

### ISSUE THREAD

**Issue by anbeng** [chochos/j8583#105]
Relates to question in https://github.com/chochos/j8583/issues/90

I have defined a composite field in field 63 

If field num 3, sub field num 2 is not present i get a null pointer exception as the code is looping through all the field parsers defined and ignores the length in LLLVAR on field num 3. 

How do I prevent this? Shouldn't the parsing stop at the length of the defined LLLVAR and not loop through all the field parsers in the composite field?

e.g.

      <field num="63" type="LLLVAR">
            <field num="1" type="ALPHA" length="12">
                <field num="1" type="ALPHA" length="1"/>
                <field num="2" type="ALPHA" length="1"/>
                <field num="3" type="ALPHA" length="5"/>
                <field num="4" type="ALPHA" length="5"/>
            </field>
            <field num="2" type="ALPHA" length="6">
                <field num="1" type="ALPHA" length="1"/>
                <field num="2" type="ALPHA" length="1"/>
                <field num="3" type="ALPHA" length="2"/>
                <field num="4" type="ALPHA" length="2"/>
            </field>
            <field num="3" type="LLLVAR">
                <field num="1" type="NUMERIC" length="24"/>
                <field num="2" type="NUMERIC" length="2"/>
      .....

Code in question:

CompositeField.java

    @Override
    public CompositeField decodeField(String value) {
        @SuppressWarnings("rawtypes")
        List<IsoValue> vals = new ArrayList<>(parsers.size());
        byte[] buf = value.getBytes();
        int pos = 0;
        try {
            **for (FieldParseInfo fpi : parsers) {**
                IsoValue<?> v = fpi.parse(0, buf, pos, fpi.getDecoder());
                if (v != null) {
                    pos += v.toString().getBytes(fpi.getCharacterEncoding()).length;
                    if (v.getType() == IsoType.LLVAR || v.getType() == IsoType.LLBIN) {
                        pos+=2;
                    } else if (v.getType() == IsoType.LLLVAR || v.getType() == IsoType.LLLBIN) {
                        pos+=3;
                    } else if (v.getType() == IsoType.LLLLBIN || v.getType() == IsoType.LLLLVAR) {
                        pos+=4;
                    }
                    vals.add(v);
                }
            }
            final CompositeField f = new CompositeField();
            f.setValues(vals);
            return f;
        } catch (ParseException | UnsupportedEncodingException ex) {
            **log.error("Decoding CompositeField", ex);
            return null;**
        }

Exception thrown:

2018-04-06 13:09:56,742 [main]  ERROR com.solab.iso8583.codecs.CompositeField  - Decoding CompositeField
java.text.ParseException: Insufficient data for ALPHA field 0 of length 1, pos 219
	at com.solab.iso8583.parse.AlphaNumericFieldParseInfo.parse(AlphaNumericFieldParseInfo.java:46)
	at com.solab.iso8583.codecs.CompositeField.decodeField(CompositeField.java:124)
	at com.solab.iso8583.codecs.CompositeField.decodeField(CompositeField.java:24)
	at com.solab.iso8583.parse.LllvarParseInfo.parse(LllvarParseInfo.java:74)
	at com.solab.iso8583.codecs.CompositeField.decodeField(CompositeField.java:124)
	at com.solab.iso8583.codecs.CompositeField.decodeField(CompositeField.java:24)
	at com.solab.iso8583.parse.LllvarParseInfo.parse(LllvarParseInfo.java:74)
	at com.solab.iso8583.MessageFactory.parseMessage(MessageFactory.java:500)
	at com.solab.iso8583.MessageFactory.parseMessage(MessageFactory.java:298)
	at ISO8583_2xx_Parser.main(ISO8583_2xx_Parser.java:28)

**Comment by chochos** [comment]
This is indirectly related to #103. Subfields of composite fields are not optional right now. There is now way for the parser to know that subfield 2 is missing.

**Comment by chochos** [comment]
There are two workarounds for your case. Bottom line, you have to include *all* subfields. But:

* For fixed-length fields, just send spaces.
* Change the fields you consider to be optional to be of type LLVAR, so you can send `00` if they're empty.
