### ISSUE TITLE
Composite Field template parsing, fields overriding and parsing exception.

### ISSUE THREAD

**Issue by maximlipiev** [chochos/j8583#39]
1) Composite field has 'LLLVAR' type instead of CompoisteField when created from template 
2) Composite field subfields overrides fields with corresponding number.
3) Message with the composite field can not be parsed back when saved to a stream.
![composite_parse](https://cloud.githubusercontent.com/assets/11855719/7348178/fb30faa4-ecf7-11e4-922d-c05aa5933993.JPG)
![composite_template](https://cloud.githubusercontent.com/assets/11855719/7348179/fb3ab7f6-ecf7-11e4-9083-8eb8e6374abb.JPG)

**Comment by chochos** [comment]
Composite fields should only be defined in a parsing guide, not in a message template.

**Comment by chochos** [comment]
I added some test code for composite field parsing and it works ok. But the message templates do not allow CompositeFields. Perhaps we could add that feature...

**Comment by chochos** [comment]
OK so this last change will fix the bug in the message template by ignoring the fields defined inside another field; only fields defined directly under the template will be processed. I'll file a separate issue to enable composite fields in templates.
