### ISSUE TITLE
Please sync gradle script with pom.xml

### ISSUE THREAD

**Issue by kpavlov** [chochos/j8583#54]
They contain different versions. Let's use either gradle or maven.

**Comment by chochos** [comment]
I guess I should get rid of the pom already... it's just that I use it to generate the site, I haven't had the time to find out how to do the same from Gradle

**Comment by dilbertside** [comment]
that's all the problem with gradle, it doesn't have the rich plugin ecosystem that Maven has.
I made a PR https://github.com/chochos/j8583/pull/78 to help you to update.

Please do not remove pom.xml, as I'm sure not every one wants to use gradle at this point.
