### ISSUE TITLE
Add Binary TPDU

### ISSUE THREAD

**Issue by jocor87** [chochos/j8583#60]
I need prepend a TPDU (10 digits in binary BCD Packed) to the message.
The header of J8583 messages only use String in ASCII.
Thanks

**Comment by chochos** [comment]
Hm, I guess we need to be able to set binary headers for binary messages...

**Comment by chochos** [comment]
Done. Now you can define a binary ISO header in the config file just by adding `binary="true"` and encode the value in hex.

**Comment by jocor87** [comment]
Hello, I have implemented the new version and it works perfect. But where can I find the new dtd?

**Comment by chochos** [comment]
Oh, crap. I'm pretty sure I haven't updated it in a while...

**Comment by chochos** [comment]
I just updated the DTD. It was long overdue. Sorry about that.

**Comment by jocor87** [comment]
Excellent, thank you.!
