### ISSUE TITLE
Prepend ISO header before length indicator

### ISSUE THREAD

**Issue by kanakisn** [chochos/j8583#68]
Hi,

first of all thanks for this very useful library. 
I am using j8583 for a protocol which needs the first byte of data expected at transport level is the first byte of the Transport Header of the protocol and not the length indicator that is present at the start of a message. The protocol defines that the length of the message should be included in a field available in the custom ISO 8583 header. 
So I would like to ask if this can be done with the j8583 library?

Thanks in advance for your help

**Comment by chochos** [comment]
The library doesn't do this. But you can generate the ISO message with `writeData()`, and append/prepend any data you need to write to sockets.
