### ISSUE TITLE
Parsing messages in server

### ISSUE THREAD

**Issue by alejodiazg** [chochos/j8583#71]
Hi, im having an issue, maybe its simple to resolve.

I create my isoMessage
when i want to send it to the server i do

`byte[] msgInByte = msg.writeData();`

send it to the server, and when I do

`IsoMessage msg2 = mf.parseMessage(msgInByte, 0);`

it fails (of course cause its expecting a header of size 0)

but then how can I parse a message without knowing its header?

this is the error  `java.text.ParseException: ISO8583 MessageFactory has no parsing guide for message type 1b3f0`

im using the example config.xml file

**Comment by JulesCizor** [comment]
Hi, could you post your config.xml on your client side and your server side ?

Because the error message is clear, there is no parsing guide for message type "1b3f0" ???
The message type in the example is 0200 for the request and 0210 for the server response.

**Comment by alejodiazg** [comment]
im currently running a single program, in the cliente side (im just testing the library)

this is the config.xml (the one used on the tests of the library)

`<?resources.xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE j8583-config PUBLIC "-//J8583//DTD CONFIG 1.0//EN"
        "http://j8583.sourceforge.net/j8583.dtd">
<j8583-config>
    

    
    <header type="0200">ISO015000050</header>
    <header type="0210">ISO015000055</header>
    <header type="0400" ref="0200" />
    <header type="0410" ref="0210" />
    <header type="0800">ISO015000015</header>
    <header type="0810" ref="0800"/>

    
    <template type="0200">
        <field num="3" type="NUMERIC" length="6">650000</field>
        <field num="32" type="LLVAR">456</field>
        <field num="35" type="LLVAR">4591700012340000=</field>
        <field num="43" type="ALPHA" length="40">SOLABTEST             TEST-3       DF MX</field>
        <field num="48" type="LLLVAR">Life, the Universe, and Everything|42</field>
        <field num="49" type="ALPHA" length="3">484</field>
        <field num="60" type="LLLVAR">B456PRO1+000</field>
        <field num="61" type="LLLVAR">        1234P vamos a meter más de 90 caracteres en este campo para comprobar si hay algun error en el parseo del mismo. Esta definido como un LLLVAR aqui por lo tanto esto debe caber sin problemas; las guias de parseo de 200 y 210 tienen LLLVAR en campo 61 tambien.</field>
        <field num="100" type="LLVAR">999</field>
        <field num="102" type="LLVAR">ABCD</field>
    </template>

    
    
    <template type="0210">
        <field num="60" type="LLLVAR">Fixed data from template</field>
        <field num="70" type="ALPHA" length="3">ABC</field>
        <field num="90" type="ALPHA" length="42">Field of length 42</field>
        <field num="100" type="LLVAR">Fixed field</field>
        <field num="102" type="LLVAR">Another fixed field</field>
        <field num="126" type="LLLVAR">...and yet another fixed field.</field>
    </template>


    <template type="0400" extends="0200">
        <field num="90" type="ALPHA" length="42">BLA</field>
        <field num="102" type="exclude" />
    </template>

    <template type="0600">
        <field num="4" type="AMOUNT">1234</field>
        <field num="11" type="NUMERIC" length="6">123</field>
        <field num="41" type="BINARY" length="8">abcdef</field>
        <field num="42" type="BINARY" length="4">abcde</field>
        <field num="43" type="ALPHA" length="40">Field of length 40</field>
        <field num="62"  type="LLBIN">0123456789abcdef620123456789abcd</field>
        <field num="63"  type="LLBIN">01234567863</field>
        <field num="64" type="LLLBIN">0123456789abcdef640123456789abcd</field>
        <field num="65" type="LLLBIN">01234567865</field>
        <field num="102" type="LLLVAR">Field of type LLLVAR</field>
    </template>

    
    <parse type="0200">
        <field num="3" type="NUMERIC" length="6" />
        <field num="4" type="AMOUNT" />
        <field num="7" type="DATE10" />
        <field num="11" type="NUMERIC" length="6" />
        <field num="12" type="TIME" />
        <field num="13" type="DATE4" />
        <field num="15" type="DATE4" />
        <field num="17" type="DATE_EXP" />
        <field num="32" type="LLVAR" />
        <field num="35" type="LLVAR" />
        <field num="37" type="NUMERIC" length="12" />
        <field num="41" type="ALPHA" length="16" />
        <field num="43" type="ALPHA" length="40" />
        <field num="48" type="LLLVAR" />
        <field num="49" type="ALPHA" length="3" />
        <field num="60" type="LLLVAR" />
        <field num="61" type="LLLVAR" />
        <field num="100" type="LLVAR" />
        <field num="102" type="LLVAR" />
    </parse>

    
    <parse type="0210">
        <field num="3" type="NUMERIC" length="6" />
        <field num="4" type="AMOUNT" />
        <field num="7" type="DATE10" />
        <field num="11" type="NUMERIC" length="6" />
        <field num="12" type="TIME" />
        <field num="13" type="DATE4" />
        <field num="15" type="DATE4" />
        <field num="17" type="DATE_EXP" />
        <field num="32" type="LLVAR" />
        <field num="35" type="LLVAR" />
        <field num="37" type="NUMERIC" length="12" />
        <field num="38" type="NUMERIC" length="6" />
        <field num="39" type="NUMERIC" length="2" />
        <field num="41" type="ALPHA" length="16" />
        <field num="43" type="ALPHA" length="40" />
        <field num="48" type="LLLVAR" />
        <field num="49" type="ALPHA" length="3" />
        <field num="60" type="LLLVAR" />
        <field num="61" type="LLLVAR" />
        <field num="70" type="ALPHA" length="3" />
        <field num="90" type="ALPHA" length="42" />
        <field num="100" type="LLVAR" />
        <field num="102" type="LLVAR" />
        <field num="126" type="LLLVAR" />
    </parse>

    
    <parse type="0600">
        <field num="4" type="AMOUNT" />
        <field num="7" type="DATE10" />
        <field num="11" type="NUMERIC" length="6" />
        <field num="41" type="BINARY" length="8" />
        <field num="42" type="BINARY" length="4" />
        <field num="43" type="ALPHA" length="40" />
        <field num="62" type="LLBIN" />
        <field num="63" type="LLBIN" />
        <field num="64" type="LLLBIN" />
        <field num="65" type="LLLBIN" />
        <field num="102" type="LLLVAR" />
    </parse>

    <parse type="0800">
        <field num="3" type="ALPHA" length="6">123456</field>
        <field num="12" type="DATE4">1231</field>
        <field num="17" type="DATE4">1231</field>
    </parse>

    <parse type="0810" extends="0800">
        <field num="17" type="exclude"/>
        <field num="39" type="ALPHA" length="2"/>
    </parse>

    <parse type="0201">
        <field num="3" type="NUMERIC" length="19" />
    </parse>
    <parse type="0202">
        <field num="3" type="NUMERIC" length="22" />
    </parse>

</j8583-config>`

I configure my messagefactory with it, then create an 0x200  message like this

`        IsoMessage msg = mf.newMessage(0x200);

        System.out.println("COMPLETE MESSAGE");

        msgWrap.printMessage(msg); //just a print function I created

        byte[] msgInByte = msg.writeData();

        //"SERVER"
        try {
            System.out.println("How the server would ge it");
            IsoMessage msg2 = mf.parseMessage(msgInByte, 0);
            msgWrap.printMessage(msg2);
        } catch (ParseException e) {
            e.printStackTrace();
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }`

The idea is to move that 'server' code to another program later, but i need to work if I can parse mesagges without knowing the header size in advance, has u can see in the xml there is a parsing guide for the message that I created.

Thanks for your response.

**Comment by JulesCizor** [comment]
Several errors are present in your example

When you write : 
`IsoMessage msg = mf.newMessage(0x200);`
According to your config.xml, the created message has the following header : 
`ISO015000050`
So a size of 12 characters

When you try to parse the created message :
`IsoMessage msg2 = mf.parseMessage(msgInByte, 0);`
You indicate that there isn't header (size = 0), so the parser processes directly the message type and doesn't recognize the message type "ISO015..." => "1b3f0" in binary

So if you don't want to use header at all, you can simply indicate it like that :
`
<header type="0200"></header>
<header type="0210">ISO015000055</header>
<header type="0400" ref="0200" />
<header type="0410" ref="0210" />
<header type="0800">ISO015000015</header>
<header type="0810" ref="0800"/>`

As for idea of
> without knowing the header size in advance
Either you know the exchange protocol with your server or you are able to calculate the header size programmatically

Hoping to have helped you

**Comment by chochos** [comment]
You're supposed to know the length of the ISO headers in advance. If you don't then there's no way to read an ISO message, with or without j8583.
