### ISSUE TITLE
newbie Config.xml file issue

### ISSUE THREAD

**Issue by Cyberblank2k** [chochos/j8583#72]
I'm sorry if this is a newb question as i'm not a Java pro. 

I've imported the J8583 jar file into an existing Web Service.I'm having an issue loading the config file that I've customized. I've placed the config.xml in the src directory of the project, and tried to load it using the following mfact = ConfigParser.createFromClasspathConfig("src/config.xml")
and mfact.setConfigPath("config.xml"). I'm still seeing an empty Messagefactory. What am i missing?

**Comment by chochos** [comment]
Well this depends on the way you set up your application/service, but usually you need to put the config file somewhere reachable by the class loader. Usually where your compiled classes are, not where the source files are (those won't go into the final app)
