### ISSUE TITLE
CustomField interface exception

### ISSUE THREAD

**Issue by akotulu** [chochos/j8583#74]
Currently CustomField parsing and encoding cannot throw exceptions which is a requirement for a banking solution I'm developing. 

``` java
public interface CustomField<T> 
{
        public T decodeField(String value) throws ParseException;

        public String encodeField(T value) throws IllegalArgumentException;
}
```

Here is how I see CustomField interface, I can throw exception when some TAG or length is invalid when parsing field.

I'm dealing with TAGLLL...999 field, so its uncommon, but as is for every ISO where you can use your own imagination how to store data.

**Comment by chochos** [comment]
You can throw runtime exceptions

**Comment by chochos** [comment]
You don't have to declare `throws` with a `RuntimeException`, so the only problem would be the `ParseException`, which I honestly don't know why they made it a checked exception.
