### ISSUE TITLE
Unable to parse extended ASCII values

### ISSUE THREAD

**Issue by Arthanarisamy** [chochos/j8583#82]
I have been using j8583 for more than two years and it works solid. Now when interfacing with one of the services, came across this issue.

After spending and debugging enough on it, my inference is that, it fails parsing extended ASCII. 
Till ASCII value 127 it works perfectly, when it reaches 080, it goes negative -128 and fails parsing the message.

https://sourceforge.net/p/j8583/discussion/689418/thread/7d71b893/

\00\EBISV0160000151210\B00\80F\80\00\00\00\00\00\00\00\00&9700000000000000000000011612291608551229065045110834986748UNI000000102+0000000001900532+0000000001900532+0000000000000000+0000000000000000+0000000001900532INR              INR003UPI0030000131179161229009

Referring to the link above,is there a way i can configure it?

**Comment by chochos** [comment]
Try setting the proper encoding in the message factory, and setting `forceEncoding` to true.

**Comment by Arthanarisamy** [comment]
I had set character encoding to UTF-8, but still unable to parse the response properly. One thing i didn't try is forceEncoding.

I was able to solve the issue, by changing the way i read bytes from socket. 
Instead of BufferedReader if i use  DataInputstream  I am able to parse the response.

I have used BufferedReader  almost in most of the sites and it is working fine throughout. Only in one particular implementation I couldn't. Jpos library is being used in this particular site. 

Any inputs on the same will be helpful for my further understanding!

**Comment by chochos** [comment]
Try `BufferedInputStream` instead of `BufferedReader`. The j8583 library is designed to work directly with bytes, precisely to avoid encoding/binary issues at the socket level.

**Comment by Arthanarisamy** [comment]
Thanks! Let me try and keep you posted!

**Comment by Arthanarisamy** [comment]
[ISOResponse.zip](https://github.com/chochos/j8583/files/1333489/ISOResponse.zip)
Using `BufferedInputStream` didn't help really.
So far using `BufferedReader` saved me in all the implementations. Now it started failing with new one.
Using `BufferedInputStream` and `BufferedReader`, not sure if it is changing the bitmap since it is a binarymap and fails parsing the ISO response message.

Attaching Sample response message.
Code used reading the response is below
````
BufferedReader lbufferedreader = null;
			InputStream linputstream = null;
			linputstream = socket.getInputStream();
			lbufferedreader = new BufferedReader(new InputStreamReader(linputstream));
			long lwaittill =  System.currentTimeMillis() + (10 * 1000) ;
			System.out.println("Buffer will wait till -:" + lwaittill);
			boolean lbufferedreaderready = false;
			while (System.currentTimeMillis() <= lwaittill) {
				if (lbufferedreader.ready()) {
					lbufferedreaderready = true;
					System.out.println("Breaking at ...:" + System.currentTimeMillis());
					break;
				}
			}
			if (lbufferedreaderready) {
				System.out.println("Ready...");
				lrespstr = "";
				int avail = linputstream.available();
				System.out.println("Availability :" + avail);
				if (linputstream.available() > 1) {
					for (int i = 0; i < avail; i++) {
						int lchar = lbufferedreader.read();
						lrespstr = lrespstr + (char) lchar;
					}
				}
			}
````

**Comment by chochos** [comment]
OK first of all, I don't see any j8583-related code in there. It's just reading from a socket with a BufferedReader, which reads characters. I don't know how you parse that later to get an IsoMessage, but it probably gets garbled. You should read bytes with a BufferedInputStream instead, and parse the resulting byte array.

**Comment by Arthanarisamy** [comment]
The read bytes are passed on to the MessageFactory `parseMessage` method.

````
                        byte[] iSOResp = getResponseBufferedReader(socket, is);
			System.out.println("iSOResp : "+ new String(iSOResp));
			URL lconfigurl = SocketClient.class.getClassLoader().getResource(CONFIG_FILE_PATH);
			MessageFactory<IsoMessage> mfact = ConfigParser.createFromUrl(lconfigurl);
			mfact.setUseBinaryBitmap(true);
			IsoMessage message = mfact.parseMessage(iSOResp, ISO_HEADER_LENGTH);
````
**Thanks a bunch**. Using BufferedInputStream helped me.
