### ISSUE TITLE
Dynamic length of parsed field

### ISSUE THREAD

**Issue by miikeFuhrer** [chochos/j8583#94]
Hi,

I'm working on iso8583 in Mexico, here we use the field 63 but it has dynamic length, an example of a 63 field is:
066& 0000400066! Q100002 0 ! ER00002 00! B400020 051510001E030015080 

So, how can i parse a dynamic field without setting it on my config.xml?

**Comment by borisokolodkov** [comment]
Maybe it's a bit late, but still, since the issue is not closed.

Field 63 is a composite field, that means it contains a set of custom fields (you can call them tokens). 
Therefore to parse it you have to know the exact type and structure of each token.

Example:
```java
IsoValue<Object> fieldValue = isoMessage.getField(63);
field = new IsoCompositeField();
field.value = String.valueOf(fieldValue.getValue());
processField63(field);

private static void processField63(IsoCompositeField field) {
    String value = field.value;  // should start with "& "
    // here you read the value string chunks and parse them manually 
    // according to each token's specs using regexps, substrings, etc.
}
```

**Comment by miikeFuhrer** [comment]
Thank you @borisokolodkov, I've resolved it!
